spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

api:
  security:
    token:
      secret: my-secret-key
#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: fiasco
#    password:
  h2:
    console:
      enabled: true
  jpa:
    database-plataform: org.hibernate.dialect.H2Dialect
    hibernate:
      dll-auto: validate
    show-sql: true
  flyway:
    enabled: true
